// <auto-generated />
namespace BlogProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_role));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251002183_new_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
